## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
from sklearn.model_selection import train_test_split
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X[:40], y[:40], test_size=10, random_state=2)

In [4]:
X_test_1

array([[135, 136, 137, 138, 139],
       [ 45,  46,  47,  48,  49],
       [ 70,  71,  72,  73,  74],
       [  0,   1,   2,   3,   4],
       [ 10,  11,  12,  13,  14],
       [150, 151, 152, 153, 154],
       [ 65,  66,  67,  68,  69],
       [180, 181, 182, 183, 184],
       [ 85,  86,  87,  88,  89],
       [185, 186, 187, 188, 189]])

In [5]:
y_test_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X[40:], y[40:], test_size=10, random_state=2)

In [7]:
X_test_2

array([[260, 261, 262, 263, 264],
       [215, 216, 217, 218, 219],
       [730, 731, 732, 733, 734],
       [230, 231, 232, 233, 234],
       [815, 816, 817, 818, 819],
       [875, 876, 877, 878, 879],
       [555, 556, 557, 558, 559],
       [900, 901, 902, 903, 904],
       [345, 346, 347, 348, 349],
       [890, 891, 892, 893, 894]])

In [8]:
y_test_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
X_test = np.concatenate((X_test_1, X_test_2), axis=0)
X_test

array([[135, 136, 137, 138, 139],
       [ 45,  46,  47,  48,  49],
       [ 70,  71,  72,  73,  74],
       [  0,   1,   2,   3,   4],
       [ 10,  11,  12,  13,  14],
       [150, 151, 152, 153, 154],
       [ 65,  66,  67,  68,  69],
       [180, 181, 182, 183, 184],
       [ 85,  86,  87,  88,  89],
       [185, 186, 187, 188, 189],
       [260, 261, 262, 263, 264],
       [215, 216, 217, 218, 219],
       [730, 731, 732, 733, 734],
       [230, 231, 232, 233, 234],
       [815, 816, 817, 818, 819],
       [875, 876, 877, 878, 879],
       [555, 556, 557, 558, 559],
       [900, 901, 902, 903, 904],
       [345, 346, 347, 348, 349],
       [890, 891, 892, 893, 894]])

In [10]:
y_test = np.concatenate((y_test_1, y_test_2), axis=0)
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])