## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

## boston

In [2]:
# 讀取資料集
boston = datasets.load_boston()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [3]:
print(regr.coef_)

[-1.14743504e-01  4.70875035e-02  8.70282354e-03  3.23818824e+00
 -1.67240567e+01  3.87662996e+00 -1.08218769e-02 -1.54144627e+00
  2.92604151e-01 -1.33989537e-02 -9.07306805e-01  8.91271054e-03
 -4.58747039e-01]


In [4]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.41


### Lasso

In [6]:
# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=1.0)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [7]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([-0.06479441,  0.04581271, -0.        ,  0.        , -0.        ,
        1.17737271,  0.011112  , -0.73717556,  0.23337442, -0.01550582,
       -0.69307422,  0.00769147, -0.69322155])

In [8]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 28.95


In [12]:
# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=0.1)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [13]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([-0.10460997,  0.04881541, -0.04507749,  1.15331258, -0.        ,
        3.81707075, -0.02085665, -1.23526694,  0.25920388, -0.01516558,
       -0.74728244,  0.00973548, -0.4998582 ])

In [14]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 26.44


In [27]:
# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=0.001)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [28]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([-1.14561044e-01,  4.71145361e-02,  7.26871520e-03,  3.21453657e+00,
       -1.63950307e+01,  3.87760778e+00, -1.10705423e-02, -1.53616665e+00,
        2.91783958e-01, -1.34201661e-02, -9.03969148e-01,  8.92800709e-03,
       -4.59277240e-01])

In [29]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.41


### Ridge

In [30]:
# 建立一個線性回歸模型
ridge = linear_model.Ridge(alpha=1.0)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [31]:
# 印出 Ridge 的參數，可以很明顯看到比起 Linear Regression，參數的數值都明顯小了許多
print(ridge.coef_)

[-1.11085562e-01  4.79127892e-02 -2.36686153e-02  2.96582333e+00
 -9.35915972e+00  3.92379527e+00 -1.73228057e-02 -1.43323726e+00
  2.74489395e-01 -1.38858412e-02 -8.31911824e-01  9.25837299e-03
 -4.67523596e-01]


In [32]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.41


In [39]:
# 建立一個線性回歸模型
ridge = linear_model.Ridge(alpha=0.001)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [40]:
# 印出 Ridge 的參數，可以很明顯看到比起 Linear Regression，參數的數值都明顯小了許多
print(ridge.coef_)

[-1.14736834e-01  4.70888594e-02  8.64460196e-03  3.23779154e+00
 -1.67109285e+01  3.87673866e+00 -1.08337565e-02 -1.54125358e+00
  2.92570618e-01 -1.33997658e-02 -9.07170231e-01  8.91332853e-03
 -4.58760462e-01]


In [41]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.41
